# Generated by Django 3.2.4 on 2021-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(max_length=100000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('vdate', models.DateField()),
                ('gdate', models.DateField()),
                ('ap', models.IntegerField(max_length=369369369)),
                ('walletype', models.CharField(max_length=3)),
                ('awAd', models.CharField(max_length=50)),
                ('bwAd', models.CharField(max_length=50)),
                ('stakingW', models.BooleanField()),
                ('stakingSD', models.DateField()),
                ('stakingDate', models.DateField()),
                ('stakingG', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
    ]
