# Generated by Django 3.2.5 on 2021-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='stakingG',
        ),
        migrations.RemoveField(
            model_name='board',
            name='text',
        ),
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='stakingV',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='ap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='awAd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='bwAd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='gdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='stakingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='stakingSD',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='stakingW',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='vdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='walletype',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
